tasks:
  - name: Build a docker with CNI
    env: 
      MYNET_CONF: |
      {
        "cniVersion": "0.2.0",
        "name": "mynet",
        "type": "bridge",
        "bridge": "cni0",
        "isGateway": true,
        "ipMasq": true,
        "ipam": {
          "type": "host-local",
          "subnet": "10.22.0.0/16",
          "routes": [{ "dst": "0.0.0.0/0" }]
        }
      }
      LOOPBACK_CONF: |
      {
        "cniVersion": "0.2.0",
        "name": "lo",
        "type": "loopback"
      }

    init: |
      echo "Install plugins"
      git clone https://github.com/containernetworking/plugins.git /workspace/plugins
      sudo mkdir -p /etc/cni/net.d
      sudo echo $MYNET_CONF >/etc/cni/net.d/10-mynet.conf
      sudo echo $LOOPBACK_CONF >/etc/cni/net.d/99-loopback.conf
      cd /workspace/plugins & /bin/bash build_linux.sh
      export CNI_PATH=/workspace/plugins/bin 
    command: |
      (
        cd $GITPOD_REPO_ROOT/scripts
        sudo CNI_PATH=$CNI_PATH ./docker-run.sh --rm busybox:latest ifconfig
      )
