additionalRepositories:
  - url: https://github.com/containernetworking/plugins
    # checkoutLocation is optional and relative to /workspaces.
    # by default the location defaults to the repository name.
    checkoutLocation: go/src/github.com/plugins

tasks:
  - name: Build a docker with CNI
    env: 
      MYNET_CONF: |
        {
          "cniVersion": "0.2.0",
          "name": "mynet",
          "type": "bridge",
          "bridge": "cni0",
          "isGateway": true,
          "ipMasq": true,
          "ipam": {
            "type": "host-local",
            "subnet": "10.22.0.0/16",
            "routes": [{ "dst": "0.0.0.0/0" }]
          }
        }
      LOOPBACK_CONF: |
        {
          "cniVersion": "0.2.0",
          "name": "lo",
          "type": "loopback"
        }
    init: |
      echo "Install plugins"
      sudo mkdir -p /etc/cni/net.d
      echo $MYNET_CONF | sudo tee -a /etc/cni/net.d/10-mynet.conf
      echo $LOOPBACK_CONF | sudo tee -a /etc/cni/net.d/99-loopback.conf
      cd /workspace/go/src/github.com/plugins & /bin/bash build_linux.sh
      export CNI_PATH=/workspace/go/src/github.com/plugins/bin
    command: |
      cd $GITPOD_REPO_ROOT/scripts
      sudo CNI_PATH=$CNI_PATH ./docker-run.sh --rm busybox:latest ifconfig
